<?php

namespace DoctrineORMModule\Proxy\__CG__\Acl\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AclPapel extends \Acl\Entity\AclPapel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'id', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'nome', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'admin', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'criadoEm', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'alteradoEm', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'pai');
        }

        return array('__isInitialized__', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'id', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'nome', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'admin', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'criadoEm', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'alteradoEm', '' . "\0" . 'Acl\\Entity\\AclPapel' . "\0" . 'pai');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AclPapel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin', array());

        return parent::getAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function getCriadoEm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriadoEm', array());

        return parent::getCriadoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlteradoEm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlteradoEm', array());

        return parent::getAlteradoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function getPai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPai', array());

        return parent::getPai();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin($admin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin', array($admin));

        return parent::setAdmin($admin);
    }

    /**
     * {@inheritDoc}
     */
    public function setCriadoEm(\DateTime $criadoEm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCriadoEm', array($criadoEm));

        return parent::setCriadoEm($criadoEm);
    }

    /**
     * {@inheritDoc}
     */
    public function setAlteradoEm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlteradoEm', array());

        return parent::setAlteradoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function setPai($pai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPai', array($pai));

        return parent::setPai($pai);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
