<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <?php if (isset($this->previous)): ?>
            <li>
                <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
                    &lt; Anterior
                </a> 
            </li>
            <?php else: ?>
            <li><span class="disabled">&lt; Anterior</span> </li>
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
                        <?php echo $page; ?>
                    </a> 
                </li>
            <?php else: ?>
                <li class="active"><a href="javascript:void(0)"><?php echo $page; ?></a> </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
            <li>
                <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
                    Próximo &gt;
                </a>
            </li>
        <?php else: ?>
            <li><span class="disabled">Próximo &gt;</span></li>
            <?php endif; ?>
    </ul>
<?php endif; ?>