<h1>Usuários</h1>

<p>
    <a href="<?= $this->url('usuario', array('action' => 'create')); ?>">Incluir</a>
</p>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Login</th>
            <th>E-Mail</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $entity) : ?>
        <tr>
            <td><?= $entity->getId()->getId();?></td>
            <td><?= $entity->getId()->getNome();?></td>
            <td><?= $entity->getLogin();?></td>
            <td><?= $entity->getEmail();?></td>
            <td>
                <a href="<?= $this->url('usuario', array('controller' => 'index', 'action' => 'update', 'key' => $entity->getId()->getId()))?>">Alterar</a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>

<br />

<?= $this->paginationControl($this->data, 'Sliding', 'paginator', array('route' => 'usuario')) ?>