<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark">
        <i class="fa fa-table fa-fw "></i> 
        Usuários 
        <span>&gt; 
            Lista
        </span>
    </h1>
</div>

<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

    <div data-widget-custombutton="false" data-widget-editbutton="false" id="wid-id-1" class="jarviswidget jarviswidget-color-blueDark jarviswidget-sortable" style="" role="widget">
        <header role="heading">
            <div class="jarviswidget-ctrls" role="menu">
                <a data-placement="bottom" title="" rel="tooltip" class="button-icon jarviswidget-toggle-btn" href="javascript:void(0);" data-original-title="Collapse">
                    <i class="fa fa-minus "></i>
                </a>
                <a data-placement="bottom" title="" rel="tooltip" class="button-icon jarviswidget-fullscreen-btn" href="javascript:void(0);" data-original-title="Fullscreen">
                    <i class="fa fa-expand "></i>
                </a>         
            </div>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>Usuário</h2>
        </header>
        <div role="content">
            
            <div class="widget-body no-padding">
                <div id="dt_basic_wrapper" class="dataTables_wrapper form-inline no-footer">
                                        
                    <div class="dt-toolbar">
                                                
                        <div class="col-xs-12 col-sm-6">
                            <div id="dt_basic_filter" class="dataTables_filter">
                                <label>
                                    <span class="input-group-addon">
                                        <i class="glyphicon glyphicon-search"></i>
                                    </span> 
                                    <input type="search" class="form-control" aria-controls="dt_basic">
                                </label>
                            </div>
                        </div>

                        <div class="col-sm-6 col-xs-12 hidden-xs">
                            <div class="pull-right dataTables_length" id="dt_basic_length">
                                <label>
                                    <select name="dt_basic_length" aria-controls="dt_basic" class="form-control">
                                        <option value="10">10</option>
                                        <option value="25">25</option>
                                        <option value="50">50</option>
                                        <option value="100">100</option>
                                    </select>
                                </label>
                            </div>
                        </div>                        
                        
                        <div class="">
                            <a href="create"><i class="btn btn-xs btn-default icon-prepend fa fa-plus"></i></a> Incluir
                        </div>                        
                        
                    </div>
                    
                    
                    <table class="table table-striped table-bordered table-hover dataTable no-footer">
                        <thead>
                            <tr>
                                <th width="6%">ID</th>
                                <th>Nome</th>
                                <th>Login</th>
                                <th>E-Mail</th>
                                <th width="7%">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->data as $entity) : ?>
                                <tr>
                                    <td><?= $entity->getId()->getId(); ?></td>
                                    <td><?= $entity->getId()->getNome(); ?></td>
                                    <td><?= $entity->getLogin(); ?></td>
                                    <td><?= $entity->getEmail(); ?></td>
                                    <td>
                                        <a href="<?= $this->url('usuario', array('controller' => 'index', 'action' => 'update', 'key' => $entity->getId()->getId())) ?>"><i class="btn btn-xs btn-default icon-prepend fa fa-pencil"></i></a>
                                        <a href="<?= $this->url('usuario', array('controller' => 'index', 'action' => 'delete', 'key' => $entity->getId()->getId())) ?>"><i class="btn btn-xs btn-default icon-prepend fa fa fa-times"></i></a>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                    <div class="dt-toolbar-footer">
                        <?= $this->paginationControl($this->data, 'Sliding', 'paginator', array('route' => 'usuario')) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>

