<h3>Editando usuário</h3>

<?php if($this->messages) : ?>
<p><?= $this->messages[0];?></p>
<?php else: ?>

<?php
$form = $this->form;
$form->setAttribute('action',$this->url('usuario', array('controller' => 'index', 'action' => 'update', 'key' => $this->key)));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>

<?php endif; ?>