<h3>Resources</h3>
<br />

<p>
    <a href="<?php echo $this->url('acl-admin/default', array('controller' => 'aclrecurso', 'action' => 'create')); ?>">Novo</a>
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Ação</th>
    </tr>

    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?php echo $entity->getId(); ?></td>
            <td><?php echo $entity->getNome(); ?></td>
            <td>
                <a href="<?php echo $this->url('acl-admin/default', array('controller' => 'aclRecurso', 'action' => 'update', 'id' => $entity->getId()));
    ?>">Editar</a>
                <a href="<?php echo $this->url('acl-admin/default', array('controller' => 'aclRecurso', 'action' => 'delete', 'id' => $entity->getId()));
    ?>">Deletar</a>
            </td>        
        </tr>
    <?php endforeach; ?>

</table>
<br />

<?= $this->paginationControl($this->data, 'Sliding', 'paginator', array('route' => 'acl-admin')) ?>
