<tr>
    <td>
        <a href="<?= $this->placeholder('url')->edit . '/' . $this->model->getId() ?>" title="Editar"><i class="fa fa-pencil fa-fw"></i></a>
        <a href="<?= $this->placeholder('url')->delete . '/' . $this->model->getId() ?>" title="Excluir"><i class="fa fa-trash-o"></i></a>
    </td>
    <td><?= $this->escapeHtml($this->model->getId()) ?></td>
    <td><?= $this->escapeHtml($this->model->getUsuario()->getLogin()) ?></td>
    <td><?= $this->escapeHtml($this->model->getNome()) ?></td>
    <td><?= $this->model->getUsuario()->getAtivo() == 1 ? 'Ativo' : 'Inativo' ?></td>
 
</tr>