<h3>Incluindo Pessoa</h3>

<br />

<?php
$form = $this->form;

$form->setAttribute('action', $this->urlAction);
$form->prepare();
echo $this->form()->openTag($form);

echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('re'));
echo $this->formRow($form->get('data_nascimento'));

echo $this->formRow($form->get('login'));
echo $this->formRow($form->get('senha'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>