<nav>
    <ul>       
        <li>
            <a href="#"><i class="fa fa-lg fa-fw fa-users"></i> <span class="menu-item-parent">Usuários</span></a>
            <ul>
                <li>
                    <a href="/pessoa">Visualizar</a>
                    <a href="/pessoa/create">Incluir</a>
                </li>                
            </ul>
        </li>        
    </ul>
</nav>
<span class="minifyme" data-action="minifyMenu"> 
    <i class="fa fa-arrow-circle-left hit"></i> 
</span>